[theme]
base            = "dark"         # se invertirá a claro si el navegador está en modo claro
primaryColor    = "#00B0FF"      # azul brillante
secondaryBackground = "#1E1E1E"
textColor       = "#FFFFFF"
font            = "sans serif"
